version: '3'
services:
  my_rest:
    build: .
    environment:
      - CONSUL_ADDR="127.0.0.1"
    ports:
      - "8080:8080"
      - "8081:8081"
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./webapp:/usr/share/nginx/html
      - ./app.conf:/etc/nginx/conf.d/default.conf
    links:
      - my_rest